update

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -13,7 +13,7 @@ on:
 jobs:
   terraform:
     runs-on: ubuntu-latest
-    timeout-minutes: 40
+    timeout-minutes: 30
 
     steps:
       - name: Checkout code
@@ -25,12 +25,10 @@ jobs:
           terraform_version: "1.10.4"
 
       - name: Terraform Init
-        run: terraform init
+        run: terraform init || { echo 'Terraform init failed' ; exit 1; }
 
-      - name: Run terraform fmt with reviewdog
-        run: |
-          terraform fmt -check -recursive | reviewdog -f=checkstyle -name="terraform fmt" -reporter=github-pr-review -level=error
+      - name: Run terraform fmt
+        run: terraform fmt -check -recursive
 
-      - name: Run terraform validate with reviewdog
-        run: |
-          terraform validate | reviewdog -f=checkstyle -name="terraform validate" -reporter=github-pr-review -level=error
+      - name: Run terraform validate
+        run: terraform validate
